package com.minduc.happabi.enums;

public enum NotificationType {
    NURSE_PROFILE_REJECTED,
    NURSE_PROFILE_APPROVED_PENDING_CONTRACT,
    NURSE_PROFILE_ACTIVE,
    NURSE_SUSPENDED,
    NURSE_REACTIVATED,
    BOOKING_PAYMENT_PENDING,
    BOOKING_PAYMENT_SUCCESS,
    BOOKING_PAYMENT_FAILED,
    BOOKING_PAYMENT_EXPIRED,
    NURSE_BOOKING_ASSIGNED,
    WORK_SESSION_UPDATED
}
