package com.minduc.happabi.enums;

public enum NurseSkill {
    POSTPARTUM_RECOVERY_MASSAGE,
    PRENATAL_RELAXATION_MASSAGE,
    FOOT_PAIN_RELIEF_MASSAGE,
    POSTPARTUM_BACK_SHOULDER_NECK_MASSAGE,
    LACTATION_STIMULATION,
    BLOCKED_MILK_DUCT_SUPPORT,
    BREAST_CARE,
    BREASTFEEDING_POSITION_GUIDANCE,
    POSTPARTUM_HEALTH_MONITORING,
    NEWBORN_BATHING,
    NEWBORN_BASIC_CARE,
    NEWBORN_HEALTH_MONITORING,
    NEWBORN_SKIN_CARE,
    HOME_NEWBORN_CARE_GUIDANCE,
    NEWBORN_WARNING_SIGN_RECOGNITION,
    PARENT_COMMUNICATION,
    MOTHER_BABY_CONSULTING,
    SITUATION_HANDLING,
    CUSTOMER_CARE,
    SCHEDULE_MANAGEMENT
}
